version: "3"
services:
  nginx:
    restart: always
    image: nginx:1.13
    ports:
      - "8000:80"
    volumes:
      - ./src:/src
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    restart: always
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/src
    links:
      # Use nginx as a proxy for xmltv in order to use the DTD from Sourceforge.
      - nginx:xmltv.xmltv.se
  fop:
    restart: always
    image: jsreportonline/fop-pdf:3
    environment:
      - temp=/tmp
