version: "3"
services:
  nginx:
    restart: always
    image: nginx:1.13
    ports:
      - "8000:80"
    volumes:
      - ./src:/src
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    restart: always
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/src
  fop:
    restart: always
    image: jsreportonline/fop-pdf:3